### ISSUE TITLE
Command to summarize the total number of orders

### ISSUE THREAD

**Issue by cesdperez** [chechtalks/lunch-bot#15]
The output should tell you which user order what. Take into account that a user can order multiple things (like empanadas) and different kind of reactions have different value associated (i.e :plus: :1: :2: :3:).

**Comment by lisandromedrano** [comment]
It can be achieved through [events](https://api.slack.com/rtm)
Events API: https://api.slack.com/events-api
Reaction Added event: https://api.slack.com/events/reaction_added
Message event: https://api.slack.com/events/message
